kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.23.4
- role: worker
  image: kindest/node:v1.23.4
- role: worker
  image: kindest/node:v1.23.4
